/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context as Context } from "./context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `Upload` scalar type represents a file upload.
     */
    upload<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Upload";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
    /**
     * The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSON";
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    jsonObject<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSONObject";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `Upload` scalar type represents a file upload.
     */
    upload<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Upload";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
    /**
     * The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSON";
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    jsonObject<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSONObject";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BuddyRequestWhereUniqueInput: { // input type
    buddy_request_id: string; // String!
  }
  ChangeImageInput: { // input type
    image_file: NexusGenScalars['Upload']; // Upload!
  }
  ChangePasswordInput: { // input type
    password: string; // String!
    token: string; // String!
  }
  ConnectTutorOrderInput: { // input type
    message_content?: string | null; // String
    student_id: string; // String!
    tutor_id: string; // String!
    tutor_order_id: string; // String!
  }
  ConversationGroupWhereUniqueInput: { // input type
    conversation_id: string; // String!
    profile_id: string; // String!
  }
  ConversationPageInput: { // input type
    cursor?: string | null; // String
    take: number; // Int!
  }
  ConversationWhereUniqueInput: { // input type
    conversation_id: string; // String!
    profile_id?: string | null; // String
  }
  CreateBuddyRequestInput: { // input type
    description: string; // String!
    extended_buddy_request_data: NexusGenScalars['JSON']; // JSON!
    profile_id: string; // String!
    purpose_name: string; // String!
    purpose_type_name: string; // String!
  }
  CreateInterestInput: { // input type
    interest_name: string; // String!
  }
  CreateNotificationInput: { // input type
    entity_id: string; // String!
    notifier_id: string; // String!
    receiver_id: string; // String!
    type_id: number; // Int!
  }
  CreateProfileInput: { // input type
    birthday?: NexusGenScalars['Date'] | null; // Date
    gender?: NexusGenEnums['Gender'] | null; // Gender
    location_name?: string | null; // String
    profile_avatar?: NexusGenScalars['Upload'] | null; // Upload
    profile_bio?: string | null; // String
  }
  CreatePurposeInput: { // input type
    purpose_description: string; // String!
    purpose_name: string; // String!
    purpose_type: NexusGenInputs['CreatePurposeTypeInput'][]; // [CreatePurposeTypeInput!]!
  }
  CreatePurposeTypeInput: { // input type
    purpose_name: string; // String!
    purpose_type_description: string; // String!
    purpose_type_name: string; // String!
  }
  CreateTutorOrderInput: { // input type
    problem: string; // String!
    student_id: string; // String!
    tutor_id?: string | null; // String
    tutor_order_interests: Array<NexusGenInputs['CreateInterestInput'] | null>; // [CreateInterestInput]!
    tutor_requirements: string; // String!
  }
  DestroyImageInput: { // input type
    img_public_id: string; // String!
  }
  EducationInput: { // input type
    current?: boolean | null; // Boolean
    education_description?: string | null; // String
    field_of_study: string; // String!
    institution_name: string; // String!
    joined_at?: NexusGenScalars['Date'] | null; // Date
    left_at?: NexusGenScalars['Date'] | null; // Date
  }
  EducationWhereUniqueInput: { // input type
    id: string; // String!
  }
  ForgotPasswordInput: { // input type
    email: string; // String!
  }
  GetManyBuddyRequestsInput: { // input type
    cursor?: string | null; // String
    search_query: string; // String!
    take: number; // Int!
  }
  GetManyProfilesInput: { // input type
    cursor?: NexusGenScalars['Date'] | null; // Date
    search_input?: string | null; // String
    take: number; // Int!
  }
  GetManyPurposeTypesInput: { // input type
    partial: boolean; // Boolean!
    purpose_type: string; // String!
  }
  GetManyPurposesInput: { // input type
    purpose_name: string; // String!
  }
  GetManyTutorOrdersInput: { // input type
    cursor?: string | null; // String
    search_input?: string | null; // String
    take: number; // Int!
  }
  GetMyBuddiesInput: { // input type
    addressee_id?: string | null; // String
    requester_id?: string | null; // String
    search_input?: string | null; // String
    take: number; // Int!
  }
  GetMyBuddyRequestsInput: { // input type
    cursor?: string | null; // String
    search_query: string; // String!
    take: number; // Int!
  }
  GetRelationshipInput: { // input type
    addressee_id: string; // String!
    requester_id: string; // String!
  }
  GetSuggestedBuddyRequests: { // input type
    cursor?: string | null; // String
    purpose_name: string[]; // [String!]!
    purpose_type_name: string[]; // [String!]!
    take: number; // Int!
  }
  GetUniquePurposeTypeInput: { // input type
    purpose_type_name: string; // String!
  }
  LoginInput: { // input type
    email: string; // String!
    password: string; // String!
  }
  MarkCompleteTutorOrderInput: { // input type
    student_id: string; // String!
    tutor_id: string; // String!
    tutor_order_id: string; // String!
  }
  NotificationWhereUniqueInput: { // input type
    id: string; // String!
  }
  ProfileWhereUniqueInput: { // input type
    profile_id: string; // ID!
  }
  ReadBuddyNotificationsInput: { // input type
    addressee_id: string; // String!
    requester_id: string; // String!
  }
  RegisterInput: { // input type
    email: string; // String!
    password: string; // String!
    username: string; // String!
  }
  RelationshipInput: { // input type
    addressee_id: string; // String!
    requester_id: string; // String!
    status: NexusGenEnums['RelationshipStatusCode']; // RelationshipStatusCode!
  }
  ResondTutorOrderConnectInput: { // input type
    status: NexusGenEnums['TutorOrderTutorConnectStatusCode']; // TutorOrderTutorConnectStatusCode!
    student_id: string; // String!
    tutor_id: string; // String!
    tutor_order_id: string; // String!
  }
  SendMessageInput: { // input type
    conversation_id: string; // String!
    message_content: string; // String!
  }
  TutorOrderWhereUniqueInput: { // input type
    id: string; // String!
  }
  UpdateBuddyRequestInput: { // input type
    description: string; // String!
    extended_buddy_request_data: NexusGenScalars['JSON']; // JSON!
    purpose_name: string; // String!
    purpose_type_name: string; // String!
  }
  UpdateProfilePurposesInput: { // input type
    profile_id: string; // String!
  }
  UpsertAgeLocationInput: { // input type
    birthday: NexusGenScalars['Date']; // Date!
    location_name: string; // String!
  }
  UpsertEducationInput: { // input type
    current: boolean; // Boolean!
    education_description?: string | null; // String
    field_of_study: string; // String!
    id?: string | null; // String
    institution_name: string; // String!
    joined_at?: NexusGenScalars['Date'] | null; // Date
    left_at?: NexusGenScalars['Date'] | null; // Date
    logo?: NexusGenScalars['Upload'] | null; // Upload
  }
  UpsertWorkExperienceInput: { // input type
    current: boolean; // Boolean!
    id?: string | null; // String
    joined_at?: NexusGenScalars['Date'] | null; // Date
    left_at?: NexusGenScalars['Date'] | null; // Date
    logo?: NexusGenScalars['Upload'] | null; // Upload
    work_description?: string | null; // String
    work_position?: string | null; // String
    workplace_name: string; // String!
  }
  VerifyEmailInput: { // input type
    token: string; // String!
  }
  WorkExperienceInput: { // input type
    current: boolean; // Boolean!
    joined_at?: NexusGenScalars['Date'] | null; // Date
    left_at?: NexusGenScalars['Date'] | null; // Date
    logo?: NexusGenScalars['Upload'] | null; // Upload
    work_description?: string | null; // String
    work_position?: string | null; // String
    workplace_name: string; // String!
  }
  WorkExperienceWhereUniqueInput: { // input type
    id: string; // String!
  }
  createGroupConversationInput: { // input type
    creator_id: string; // String!
    member_ids: string[]; // [String!]!
    message_content?: string | null; // String
  }
  getManyInterestsInput: { // input type
    search_input?: string | null; // String
  }
  initConversationInput: { // input type
    addressee_id: string; // String!
    requester_id: string; // String!
  }
  updateIntroductionInput: { // input type
    profile_bio: string; // String!
  }
}

export interface NexusGenEnums {
  Gender: "FEMALE" | "MALE" | "OTHERS"
  RelationshipStatusCode: "ACCEPTED" | "DECLINED" | "REQUESTED"
  TutorOrderTutorConnectStatusCode: "ACCEPTED" | "DECLINED" | "REQUESTED"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
  JSON: any
  JSONObject: any
  Upload: any
}

export interface NexusGenObjects {
  AuthOutput: { // root type
    ErrorFieldOutput?: NexusGenRootTypes['ErrorFieldOutput'][] | null; // [ErrorFieldOutput!]
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    User?: NexusGenRootTypes['User'] | null; // User
  }
  BuddyNotificationOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    PageInfo?: NexusGenRootTypes['PageInfoIDCursor'] | null; // PageInfoIDCursor
    buddyAccepts?: NexusGenRootTypes['Relationship'][] | null; // [Relationship!]
    buddyRequests?: NexusGenRootTypes['Relationship'][] | null; // [Relationship!]
    countNotViewedBuddyNotifications?: number | null; // Int
  }
  BuddyRequest: { // root type
    buddy_requester_id: string; // String!
    description: string; // String!
    extended_buddy_request_data?: NexusGenScalars['JSON'] | null; // JSON
    id: string; // ID!
    purpose_id: string; // String!
    purpose_type_id: string; // String!
  }
  CompoundIDEndCursor: { // root type
    id_1?: string | null; // String
    id_2?: string | null; // String
  }
  Conversation: { // root type
    conversation_avatar?: string | null; // String
    conversation_name?: string | null; // String
    id: string; // String!
  }
  ConversationGroup: { // root type
    conversation_id: string; // String!
    conversation_member_id: string; // String!
    isRead: boolean; // Boolean!
    isViewed: boolean; // Boolean!
    joined_at: NexusGenScalars['Date']; // Date!
    left_at?: NexusGenScalars['Date'] | null; // Date
  }
  CreateBuddyRequestOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    buddy_request?: NexusGenRootTypes['BuddyRequest'] | null; // BuddyRequest
  }
  CreatePurposeTypeOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    purpose_type?: NexusGenRootTypes['PurposeType'] | null; // PurposeType
  }
  Education: { // root type
    current: boolean; // Boolean!
    education_description?: string | null; // String
    field_of_study: string; // String!
    id: string; // String!
    institution_name: string; // String!
    joined_at?: NexusGenScalars['Date'] | null; // Date
    left_at?: NexusGenScalars['Date'] | null; // Date
    logo?: string | null; // String
    logo_public_id?: string | null; // String
  }
  ErrorFieldOutput: { // root type
    field: string; // String!
    message: string; // String!
  }
  GetManyBuddyRequestsOutput: { // root type
    BuddyRequestPageInfo?: NexusGenRootTypes['PageInfoIDCursor'] | null; // PageInfoIDCursor
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    buddy_requests?: NexusGenRootTypes['BuddyRequest'][] | null; // [BuddyRequest!]
  }
  GetManyInterestOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    Interest?: Array<NexusGenRootTypes['Interest'] | null> | null; // [Interest]
  }
  GetManyProfilesOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    PageInfo?: NexusGenRootTypes['PageInfoDataCursor'] | null; // PageInfoDataCursor
    Profile?: Array<NexusGenRootTypes['Profile'] | null> | null; // [Profile]
  }
  GetManyPurposeTypesOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    purpose_types?: NexusGenRootTypes['PurposeType'][] | null; // [PurposeType!]
  }
  GetManyPurposesOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    purposes?: NexusGenRootTypes['Purpose'][] | null; // [Purpose!]
  }
  GetManyTutorOrderTutorConnect: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    tutor_order_tutor_connect?: Array<NexusGenRootTypes['TutorOrderTutorConnect'] | null> | null; // [TutorOrderTutorConnect]
  }
  GetManyTutorOrdersOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    PageInfoIDCursor?: NexusGenRootTypes['PageInfoIDCursor'] | null; // PageInfoIDCursor
    tutor_order?: NexusGenRootTypes['TutorOrder'][] | null; // [TutorOrder!]
  }
  GetMyBuddiesOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    PageInfo?: NexusGenRootTypes['PageInfoCompoundIDCursor'] | null; // PageInfoCompoundIDCursor
    relationships?: NexusGenRootTypes['Relationship'][] | null; // [Relationship!]
  }
  GetNotificationOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    countNotViewedNotifications?: number | null; // Int
    notifications?: Array<NexusGenRootTypes['Notification'] | null> | null; // [Notification]
  }
  GetRelationshipOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    otherEndRelationship?: NexusGenRootTypes['Relationship'] | null; // Relationship
    relationship?: NexusGenRootTypes['Relationship'] | null; // Relationship
  }
  GetTutorOrderTutorConnectOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    tutor_order_tutor_connect?: NexusGenRootTypes['TutorOrderTutorConnect'] | null; // TutorOrderTutorConnect
  }
  GetUniquePurposeType: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    purpose_type?: NexusGenRootTypes['PurposeType'] | null; // PurposeType
  }
  IOutput: { // root type
    code: number; // Int!
    message: string; // String!
    success: boolean; // Boolean!
  }
  Interest: { // root type
    id: string; // ID!
    interest_name?: string | null; // String
  }
  Location: { // root type
    id: number; // Int!
    location_name: string; // String!
  }
  Message: { // root type
    conversation_id: string; // String!
    createdAt?: NexusGenScalars['Date'] | null; // Date
    id: string; // String!
    message_author_id: string; // String!
    message_content: string; // String!
  }
  Mutation: {};
  Notification: { // root type
    createdAt: NexusGenScalars['Date']; // Date!
    entity_id?: string | null; // String
    id: string; // String!
    isRead: boolean; // Boolean!
    isViewed: boolean; // Boolean!
    message?: string | null; // String
    notifier_id: string; // String!
    receiver_id: string; // String!
    type_id: number; // Int!
  }
  NotificationMutationOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
  }
  PageInfoCompoundIDCursor: { // root type
    endCursor?: NexusGenRootTypes['CompoundIDEndCursor'] | null; // CompoundIDEndCursor
    hasNextPage: boolean; // Boolean!
    lastTake?: number | null; // Int
  }
  PageInfoDataCursor: { // root type
    endCursor?: NexusGenScalars['Date'] | null; // Date
    hasNextPage: boolean; // Boolean!
    lastTake?: number | null; // Int
  }
  PageInfoIDCursor: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    lastTake?: number | null; // Int
  }
  Profile: { // root type
    birthday?: NexusGenScalars['Date'] | null; // Date
    createdAt?: NexusGenScalars['Date'] | null; // Date
    gender?: NexusGenEnums['Gender'] | null; // Gender
    id: string; // ID!
    location_id?: number | null; // Int
    profile_avatar?: string | null; // String
    profile_avatar_public_id?: string | null; // String
    profile_bio?: string | null; // String
    profile_wallpaper?: string | null; // String
    profile_wallpaper_public_id?: string | null; // String
    tutor_mode: boolean; // Boolean!
  }
  ProfileInterest: { // root type
    interest_id: string; // ID!
    profile_id: string; // ID!
  }
  ProfileMutationOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    Profile?: NexusGenRootTypes['Profile'] | null; // Profile
  }
  Purpose: { // root type
    id: string; // ID!
    purpose_description: string; // String!
    purpose_name: string; // String!
  }
  PurposeType: { // root type
    extened_purpose_type_data?: NexusGenScalars['JSON'] | null; // JSON
    id: string; // ID!
    purpose_id: string; // String!
    purpose_type_description: string; // String!
    purpose_type_name: string; // String!
  }
  Query: {};
  Relationship: { // root type
    addressee_id: string; // String!
    conversation_id?: string | null; // String
    createdAt: NexusGenScalars['Date']; // Date!
    isRead: boolean; // Boolean!
    isViewed: boolean; // Boolean!
    requester_id: string; // String!
    status: NexusGenEnums['RelationshipStatusCode']; // RelationshipStatusCode!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  RelationshipOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    otherEndRelationship?: NexusGenRootTypes['Relationship'] | null; // Relationship
    relationship?: NexusGenRootTypes['Relationship'] | null; // Relationship
  }
  SendMessageOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    Message?: NexusGenRootTypes['Message'] | null; // Message
  }
  Subscription: {};
  TutorOrder: { // root type
    createdAt: NexusGenScalars['Date']; // Date!
    id: string; // String!
    isCompleted: boolean; // Boolean!
    problem: string; // String!
    student_id: string; // String!
    tutor_id?: string | null; // String
    tutor_requirements: string; // String!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  TutorOrderInterests: { // root type
    interest_id: string; // String!
    tutor_order_id: string; // String!
  }
  TutorOrderOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    tutor_order?: NexusGenRootTypes['TutorOrder'] | null; // TutorOrder
  }
  TutorOrderTutorConnect: { // root type
    status: NexusGenEnums['TutorOrderTutorConnectStatusCode']; // TutorOrderTutorConnectStatusCode!
    tutor_id: string; // String!
    tutor_order_id: string; // String!
  }
  UpdateProfilePurposesOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
  }
  UpsertEducationOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    education?: NexusGenRootTypes['Education'] | null; // Education
  }
  UpsertWorkExperienceOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    work_experience?: NexusGenRootTypes['WorkExperience'] | null; // WorkExperience
  }
  User: { // root type
    email: string; // String!
    id: string; // ID!
    isVerified: boolean; // Boolean!
    username: string; // String!
  }
  WorkExperience: { // root type
    current: boolean; // Boolean!
    id: string; // String!
    joined_at?: NexusGenScalars['Date'] | null; // Date
    left_at?: NexusGenScalars['Date'] | null; // Date
    logo?: string | null; // String
    logo_public_id?: string | null; // String
    profile_id: string; // String!
    work_description?: string | null; // String
    work_position?: string | null; // String
    workplace_name: string; // String!
  }
  createPurposeOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
  }
  getConversationOutput: { // root type
    Conversation?: NexusGenRootTypes['Conversation'] | null; // Conversation
    ConversationPageInfo?: NexusGenRootTypes['PageInfoIDCursor'] | null; // PageInfoIDCursor
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    Messages?: NexusGenRootTypes['Message'][] | null; // [Message!]
  }
  getManyConversationPutput: { // root type
    Conversations?: NexusGenRootTypes['ConversationGroup'][] | null; // [ConversationGroup!]
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    countNotViewedConversation?: number | null; // Int
  }
  initConversationOutput: { // root type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    conversation?: NexusGenRootTypes['Conversation'] | null; // Conversation
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthOutput: { // field return type
    ErrorFieldOutput: NexusGenRootTypes['ErrorFieldOutput'][] | null; // [ErrorFieldOutput!]
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    User: NexusGenRootTypes['User'] | null; // User
  }
  BuddyNotificationOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    PageInfo: NexusGenRootTypes['PageInfoIDCursor'] | null; // PageInfoIDCursor
    buddyAccepts: NexusGenRootTypes['Relationship'][] | null; // [Relationship!]
    buddyRequests: NexusGenRootTypes['Relationship'][] | null; // [Relationship!]
    countNotViewedBuddyNotifications: number | null; // Int
  }
  BuddyRequest: { // field return type
    buddy_requester: NexusGenRootTypes['Profile']; // Profile!
    buddy_requester_id: string; // String!
    description: string; // String!
    extended_buddy_request_data: NexusGenScalars['JSON'] | null; // JSON
    id: string; // ID!
    purpose: NexusGenRootTypes['Purpose']; // Purpose!
    purpose_id: string; // String!
    purpose_type: NexusGenRootTypes['PurposeType']; // PurposeType!
    purpose_type_id: string; // String!
  }
  CompoundIDEndCursor: { // field return type
    id_1: string | null; // String
    id_2: string | null; // String
  }
  Conversation: { // field return type
    conversation_avatar: string | null; // String
    conversation_latest_message: NexusGenRootTypes['Message'] | null; // Message
    conversation_member: NexusGenRootTypes['Profile'][]; // [Profile!]!
    conversation_name: string | null; // String
    id: string; // String!
  }
  ConversationGroup: { // field return type
    conversation: NexusGenRootTypes['Conversation']; // Conversation!
    conversation_id: string; // String!
    conversation_member_id: string; // String!
    isRead: boolean; // Boolean!
    isViewed: boolean; // Boolean!
    joined_at: NexusGenScalars['Date']; // Date!
    left_at: NexusGenScalars['Date'] | null; // Date
  }
  CreateBuddyRequestOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    buddy_request: NexusGenRootTypes['BuddyRequest'] | null; // BuddyRequest
  }
  CreatePurposeTypeOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    purpose_type: NexusGenRootTypes['PurposeType'] | null; // PurposeType
  }
  Education: { // field return type
    current: boolean; // Boolean!
    education_description: string | null; // String
    field_of_study: string; // String!
    id: string; // String!
    institution_name: string; // String!
    joined_at: NexusGenScalars['Date'] | null; // Date
    left_at: NexusGenScalars['Date'] | null; // Date
    logo: string | null; // String
    logo_public_id: string | null; // String
  }
  ErrorFieldOutput: { // field return type
    field: string; // String!
    message: string; // String!
  }
  GetManyBuddyRequestsOutput: { // field return type
    BuddyRequestPageInfo: NexusGenRootTypes['PageInfoIDCursor'] | null; // PageInfoIDCursor
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    buddy_requests: NexusGenRootTypes['BuddyRequest'][] | null; // [BuddyRequest!]
  }
  GetManyInterestOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    Interest: Array<NexusGenRootTypes['Interest'] | null> | null; // [Interest]
  }
  GetManyProfilesOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    PageInfo: NexusGenRootTypes['PageInfoDataCursor'] | null; // PageInfoDataCursor
    Profile: Array<NexusGenRootTypes['Profile'] | null> | null; // [Profile]
  }
  GetManyPurposeTypesOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    purpose_types: NexusGenRootTypes['PurposeType'][] | null; // [PurposeType!]
  }
  GetManyPurposesOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    purposes: NexusGenRootTypes['Purpose'][] | null; // [Purpose!]
  }
  GetManyTutorOrderTutorConnect: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    tutor_order_tutor_connect: Array<NexusGenRootTypes['TutorOrderTutorConnect'] | null> | null; // [TutorOrderTutorConnect]
  }
  GetManyTutorOrdersOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    PageInfoIDCursor: NexusGenRootTypes['PageInfoIDCursor'] | null; // PageInfoIDCursor
    tutor_order: NexusGenRootTypes['TutorOrder'][] | null; // [TutorOrder!]
  }
  GetMyBuddiesOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    PageInfo: NexusGenRootTypes['PageInfoCompoundIDCursor'] | null; // PageInfoCompoundIDCursor
    relationships: NexusGenRootTypes['Relationship'][] | null; // [Relationship!]
  }
  GetNotificationOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    countNotViewedNotifications: number | null; // Int
    notifications: Array<NexusGenRootTypes['Notification'] | null> | null; // [Notification]
  }
  GetRelationshipOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    otherEndRelationship: NexusGenRootTypes['Relationship'] | null; // Relationship
    relationship: NexusGenRootTypes['Relationship'] | null; // Relationship
  }
  GetTutorOrderTutorConnectOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    tutor_order_tutor_connect: NexusGenRootTypes['TutorOrderTutorConnect'] | null; // TutorOrderTutorConnect
  }
  GetUniquePurposeType: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    purpose_type: NexusGenRootTypes['PurposeType'] | null; // PurposeType
  }
  IOutput: { // field return type
    code: number; // Int!
    message: string; // String!
    success: boolean; // Boolean!
  }
  Interest: { // field return type
    id: string; // ID!
    interest_name: string | null; // String
    profile_interests: NexusGenRootTypes['ProfileInterest'][]; // [ProfileInterest!]!
  }
  Location: { // field return type
    id: number; // Int!
    location_name: string; // String!
  }
  Message: { // field return type
    author: NexusGenRootTypes['Profile']; // Profile!
    conversation_id: string; // String!
    createdAt: NexusGenScalars['Date'] | null; // Date
    id: string; // String!
    message_author_id: string; // String!
    message_content: string; // String!
  }
  Mutation: { // field return type
    changePassword: NexusGenRootTypes['AuthOutput'] | null; // AuthOutput
    connectBuddy: NexusGenRootTypes['RelationshipOutput'] | null; // RelationshipOutput
    connectTutorOrder: NexusGenRootTypes['TutorOrderOutput'] | null; // TutorOrderOutput
    createBuddyRequest: NexusGenRootTypes['CreateBuddyRequestOutput'] | null; // CreateBuddyRequestOutput
    createGroupConversation: NexusGenRootTypes['initConversationOutput'] | null; // initConversationOutput
    createProfile: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    createPurposeType: NexusGenRootTypes['CreatePurposeTypeOutput'] | null; // CreatePurposeTypeOutput
    createTutorOrder: NexusGenRootTypes['TutorOrderOutput'] | null; // TutorOrderOutput
    deleteEducation: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    deleteTutorOrder: NexusGenRootTypes['TutorOrderOutput'] | null; // TutorOrderOutput
    deleteTutorOrderConnect: NexusGenRootTypes['TutorOrderOutput'] | null; // TutorOrderOutput
    deleteWorkExperience: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    forgotPassword: NexusGenRootTypes['AuthOutput'] | null; // AuthOutput
    initConversation: NexusGenRootTypes['initConversationOutput'] | null; // initConversationOutput
    login: NexusGenRootTypes['AuthOutput']; // AuthOutput!
    logout: NexusGenRootTypes['AuthOutput']; // AuthOutput!
    markCompleteTutorOrder: NexusGenRootTypes['TutorOrderOutput'] | null; // TutorOrderOutput
    readBuddyNotifications: NexusGenRootTypes['BuddyNotificationOutput'] | null; // BuddyNotificationOutput
    readMessage: NexusGenRootTypes['IOutput'] | null; // IOutput
    readNotification: NexusGenRootTypes['NotificationMutationOutput'] | null; // NotificationMutationOutput
    register: NexusGenRootTypes['AuthOutput']; // AuthOutput!
    removeAvatar: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    removeBuddy: NexusGenRootTypes['RelationshipOutput'] | null; // RelationshipOutput
    removeWallpaper: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    respondBuddy: NexusGenRootTypes['RelationshipOutput'] | null; // RelationshipOutput
    respondTutorOrderConnect: NexusGenRootTypes['TutorOrderOutput'] | null; // TutorOrderOutput
    sendMessage: NexusGenRootTypes['SendMessageOutput'] | null; // SendMessageOutput
    updateAvatar: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    updateBuddyRequest: NexusGenRootTypes['CreateBuddyRequestOutput'] | null; // CreateBuddyRequestOutput
    updateIntroduction: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    updateTutorOrder: NexusGenRootTypes['TutorOrderOutput'] | null; // TutorOrderOutput
    updateWallpaper: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    upsertAgeLocation: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    upsertEducation: NexusGenRootTypes['UpsertEducationOutput'] | null; // UpsertEducationOutput
    upsertWorkExperience: NexusGenRootTypes['UpsertWorkExperienceOutput'] | null; // UpsertWorkExperienceOutput
    verifyEmail: NexusGenRootTypes['AuthOutput']; // AuthOutput!
    viewBuddyNotifications: NexusGenRootTypes['BuddyNotificationOutput'] | null; // BuddyNotificationOutput
    viewMessage: NexusGenRootTypes['IOutput'] | null; // IOutput
    viewNotification: NexusGenRootTypes['NotificationMutationOutput'] | null; // NotificationMutationOutput
  }
  Notification: { // field return type
    createdAt: NexusGenScalars['Date']; // Date!
    entity_id: string | null; // String
    id: string; // String!
    isRead: boolean; // Boolean!
    isViewed: boolean; // Boolean!
    message: string | null; // String
    notifier: NexusGenRootTypes['Profile'] | null; // Profile
    notifier_id: string; // String!
    receiver_id: string; // String!
    type_id: number; // Int!
  }
  NotificationMutationOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
  }
  PageInfoCompoundIDCursor: { // field return type
    endCursor: NexusGenRootTypes['CompoundIDEndCursor'] | null; // CompoundIDEndCursor
    hasNextPage: boolean; // Boolean!
    lastTake: number | null; // Int
  }
  PageInfoDataCursor: { // field return type
    endCursor: NexusGenScalars['Date'] | null; // Date
    hasNextPage: boolean; // Boolean!
    lastTake: number | null; // Int
  }
  PageInfoIDCursor: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    lastTake: number | null; // Int
  }
  Profile: { // field return type
    birthday: NexusGenScalars['Date'] | null; // Date
    createdAt: NexusGenScalars['Date'] | null; // Date
    education: Array<NexusGenRootTypes['Education'] | null> | null; // [Education]
    gender: NexusGenEnums['Gender'] | null; // Gender
    id: string; // ID!
    location: NexusGenRootTypes['Location'] | null; // Location
    location_id: number | null; // Int
    profile_avatar: string | null; // String
    profile_avatar_public_id: string | null; // String
    profile_bio: string | null; // String
    profile_wallpaper: string | null; // String
    profile_wallpaper_public_id: string | null; // String
    tutor_mode: boolean; // Boolean!
    user: NexusGenRootTypes['User'] | null; // User
    work_experience: Array<NexusGenRootTypes['WorkExperience'] | null> | null; // [WorkExperience]
  }
  ProfileInterest: { // field return type
    interest: NexusGenRootTypes['Interest']; // Interest!
    interest_id: string; // ID!
    profile: NexusGenRootTypes['Profile']; // Profile!
    profile_id: string; // ID!
  }
  ProfileMutationOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    Profile: NexusGenRootTypes['Profile'] | null; // Profile
  }
  Purpose: { // field return type
    id: string; // ID!
    purpose_description: string; // String!
    purpose_name: string; // String!
    purpose_type: Array<NexusGenRootTypes['PurposeType'] | null> | null; // [PurposeType]
  }
  PurposeType: { // field return type
    extened_purpose_type_data: NexusGenScalars['JSON'] | null; // JSON
    id: string; // ID!
    purpose: NexusGenRootTypes['Purpose']; // Purpose!
    purpose_id: string; // String!
    purpose_type_description: string; // String!
    purpose_type_name: string; // String!
  }
  Query: { // field return type
    getBuddyNotifications: NexusGenRootTypes['BuddyNotificationOutput'] | null; // BuddyNotificationOutput
    getConversation: NexusGenRootTypes['getConversationOutput'] | null; // getConversationOutput
    getManyBuddyRequests: NexusGenRootTypes['GetManyBuddyRequestsOutput'] | null; // GetManyBuddyRequestsOutput
    getManyConversations: NexusGenRootTypes['getManyConversationPutput'] | null; // getManyConversationPutput
    getManyInterests: NexusGenRootTypes['GetManyInterestOutput'] | null; // GetManyInterestOutput
    getManyProfiles: NexusGenRootTypes['GetManyProfilesOutput'] | null; // GetManyProfilesOutput
    getManyPurposeTypes: NexusGenRootTypes['GetManyPurposeTypesOutput'] | null; // GetManyPurposeTypesOutput
    getManyPurposes: NexusGenRootTypes['GetManyPurposesOutput'] | null; // GetManyPurposesOutput
    getManyTutorOrderRequests: NexusGenRootTypes['GetManyTutorOrderTutorConnect'] | null; // GetManyTutorOrderTutorConnect
    getManyTutorOrders: NexusGenRootTypes['GetManyTutorOrdersOutput'] | null; // GetManyTutorOrdersOutput
    getMyBuddies: NexusGenRootTypes['GetMyBuddiesOutput'] | null; // GetMyBuddiesOutput
    getMyBuddiesRequests: NexusGenRootTypes['GetMyBuddiesOutput'] | null; // GetMyBuddiesOutput
    getMyBuddyRequests: NexusGenRootTypes['GetManyBuddyRequestsOutput'] | null; // GetManyBuddyRequestsOutput
    getMyTutorOrder: NexusGenRootTypes['GetManyTutorOrdersOutput'] | null; // GetManyTutorOrdersOutput
    getNotifications: NexusGenRootTypes['GetNotificationOutput'] | null; // GetNotificationOutput
    getProfile: NexusGenRootTypes['ProfileMutationOutput'] | null; // ProfileMutationOutput
    getRelationship: NexusGenRootTypes['GetRelationshipOutput'] | null; // GetRelationshipOutput
    getSuggestedBuddyRequests: NexusGenRootTypes['GetManyBuddyRequestsOutput'] | null; // GetManyBuddyRequestsOutput
    getTutorOrder: NexusGenRootTypes['TutorOrderOutput'] | null; // TutorOrderOutput
    getTutorOrderTutorConnect: NexusGenRootTypes['GetTutorOrderTutorConnectOutput'] | null; // GetTutorOrderTutorConnectOutput
    getUniquePurposeType: NexusGenRootTypes['GetUniquePurposeType'] | null; // GetUniquePurposeType
    getUser: NexusGenRootTypes['User'] | null; // User
  }
  Relationship: { // field return type
    addressee: NexusGenRootTypes['Profile']; // Profile!
    addressee_id: string; // String!
    conversation_id: string | null; // String
    createdAt: NexusGenScalars['Date']; // Date!
    isRead: boolean; // Boolean!
    isViewed: boolean; // Boolean!
    requester: NexusGenRootTypes['Profile']; // Profile!
    requester_id: string; // String!
    status: NexusGenEnums['RelationshipStatusCode']; // RelationshipStatusCode!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  RelationshipOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    otherEndRelationship: NexusGenRootTypes['Relationship'] | null; // Relationship
    relationship: NexusGenRootTypes['Relationship'] | null; // Relationship
  }
  SendMessageOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    Message: NexusGenRootTypes['Message'] | null; // Message
  }
  Subscription: { // field return type
    getBuddyNotifications: NexusGenRootTypes['BuddyNotificationOutput'] | null; // BuddyNotificationOutput
    getConversation: NexusGenRootTypes['getConversationOutput'] | null; // getConversationOutput
    getManyConversations: NexusGenRootTypes['getManyConversationPutput'] | null; // getManyConversationPutput
    getNotifications: NexusGenRootTypes['GetNotificationOutput'] | null; // GetNotificationOutput
  }
  TutorOrder: { // field return type
    createdAt: NexusGenScalars['Date']; // Date!
    id: string; // String!
    isCompleted: boolean; // Boolean!
    problem: string; // String!
    student: NexusGenRootTypes['Profile']; // Profile!
    student_id: string; // String!
    tutor: NexusGenRootTypes['Profile'] | null; // Profile
    tutor_id: string | null; // String
    tutor_order_interest: NexusGenRootTypes['TutorOrderInterests'][] | null; // [TutorOrderInterests!]
    tutor_requirements: string; // String!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  TutorOrderInterests: { // field return type
    interest: NexusGenRootTypes['Interest']; // Interest!
    interest_id: string; // String!
    tutor_order: NexusGenRootTypes['TutorOrder']; // TutorOrder!
    tutor_order_id: string; // String!
  }
  TutorOrderOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    tutor_order: NexusGenRootTypes['TutorOrder'] | null; // TutorOrder
  }
  TutorOrderTutorConnect: { // field return type
    status: NexusGenEnums['TutorOrderTutorConnectStatusCode']; // TutorOrderTutorConnectStatusCode!
    tutor: NexusGenRootTypes['Profile']; // Profile!
    tutor_id: string; // String!
    tutor_order: NexusGenRootTypes['TutorOrder']; // TutorOrder!
    tutor_order_id: string; // String!
  }
  UpdateProfilePurposesOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
  }
  UpsertEducationOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    education: NexusGenRootTypes['Education'] | null; // Education
  }
  UpsertWorkExperienceOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    work_experience: NexusGenRootTypes['WorkExperience'] | null; // WorkExperience
  }
  User: { // field return type
    email: string; // String!
    id: string; // ID!
    isVerified: boolean; // Boolean!
    profile: NexusGenRootTypes['Profile'] | null; // Profile
    username: string; // String!
  }
  WorkExperience: { // field return type
    current: boolean; // Boolean!
    id: string; // String!
    joined_at: NexusGenScalars['Date'] | null; // Date
    left_at: NexusGenScalars['Date'] | null; // Date
    logo: string | null; // String
    logo_public_id: string | null; // String
    profile_id: string; // String!
    work_description: string | null; // String
    work_position: string | null; // String
    workplace_name: string; // String!
  }
  createPurposeOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
  }
  getConversationOutput: { // field return type
    Conversation: NexusGenRootTypes['Conversation'] | null; // Conversation
    ConversationPageInfo: NexusGenRootTypes['PageInfoIDCursor'] | null; // PageInfoIDCursor
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    Messages: NexusGenRootTypes['Message'][] | null; // [Message!]
  }
  getManyConversationPutput: { // field return type
    Conversations: NexusGenRootTypes['ConversationGroup'][] | null; // [ConversationGroup!]
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    countNotViewedConversation: number | null; // Int
  }
  initConversationOutput: { // field return type
    IOutput: NexusGenRootTypes['IOutput']; // IOutput!
    conversation: NexusGenRootTypes['Conversation'] | null; // Conversation
  }
}

export interface NexusGenFieldTypeNames {
  AuthOutput: { // field return type name
    ErrorFieldOutput: 'ErrorFieldOutput'
    IOutput: 'IOutput'
    User: 'User'
  }
  BuddyNotificationOutput: { // field return type name
    IOutput: 'IOutput'
    PageInfo: 'PageInfoIDCursor'
    buddyAccepts: 'Relationship'
    buddyRequests: 'Relationship'
    countNotViewedBuddyNotifications: 'Int'
  }
  BuddyRequest: { // field return type name
    buddy_requester: 'Profile'
    buddy_requester_id: 'String'
    description: 'String'
    extended_buddy_request_data: 'JSON'
    id: 'ID'
    purpose: 'Purpose'
    purpose_id: 'String'
    purpose_type: 'PurposeType'
    purpose_type_id: 'String'
  }
  CompoundIDEndCursor: { // field return type name
    id_1: 'String'
    id_2: 'String'
  }
  Conversation: { // field return type name
    conversation_avatar: 'String'
    conversation_latest_message: 'Message'
    conversation_member: 'Profile'
    conversation_name: 'String'
    id: 'String'
  }
  ConversationGroup: { // field return type name
    conversation: 'Conversation'
    conversation_id: 'String'
    conversation_member_id: 'String'
    isRead: 'Boolean'
    isViewed: 'Boolean'
    joined_at: 'Date'
    left_at: 'Date'
  }
  CreateBuddyRequestOutput: { // field return type name
    IOutput: 'IOutput'
    buddy_request: 'BuddyRequest'
  }
  CreatePurposeTypeOutput: { // field return type name
    IOutput: 'IOutput'
    purpose_type: 'PurposeType'
  }
  Education: { // field return type name
    current: 'Boolean'
    education_description: 'String'
    field_of_study: 'String'
    id: 'String'
    institution_name: 'String'
    joined_at: 'Date'
    left_at: 'Date'
    logo: 'String'
    logo_public_id: 'String'
  }
  ErrorFieldOutput: { // field return type name
    field: 'String'
    message: 'String'
  }
  GetManyBuddyRequestsOutput: { // field return type name
    BuddyRequestPageInfo: 'PageInfoIDCursor'
    IOutput: 'IOutput'
    buddy_requests: 'BuddyRequest'
  }
  GetManyInterestOutput: { // field return type name
    IOutput: 'IOutput'
    Interest: 'Interest'
  }
  GetManyProfilesOutput: { // field return type name
    IOutput: 'IOutput'
    PageInfo: 'PageInfoDataCursor'
    Profile: 'Profile'
  }
  GetManyPurposeTypesOutput: { // field return type name
    IOutput: 'IOutput'
    purpose_types: 'PurposeType'
  }
  GetManyPurposesOutput: { // field return type name
    IOutput: 'IOutput'
    purposes: 'Purpose'
  }
  GetManyTutorOrderTutorConnect: { // field return type name
    IOutput: 'IOutput'
    tutor_order_tutor_connect: 'TutorOrderTutorConnect'
  }
  GetManyTutorOrdersOutput: { // field return type name
    IOutput: 'IOutput'
    PageInfoIDCursor: 'PageInfoIDCursor'
    tutor_order: 'TutorOrder'
  }
  GetMyBuddiesOutput: { // field return type name
    IOutput: 'IOutput'
    PageInfo: 'PageInfoCompoundIDCursor'
    relationships: 'Relationship'
  }
  GetNotificationOutput: { // field return type name
    IOutput: 'IOutput'
    countNotViewedNotifications: 'Int'
    notifications: 'Notification'
  }
  GetRelationshipOutput: { // field return type name
    IOutput: 'IOutput'
    otherEndRelationship: 'Relationship'
    relationship: 'Relationship'
  }
  GetTutorOrderTutorConnectOutput: { // field return type name
    IOutput: 'IOutput'
    tutor_order_tutor_connect: 'TutorOrderTutorConnect'
  }
  GetUniquePurposeType: { // field return type name
    IOutput: 'IOutput'
    purpose_type: 'PurposeType'
  }
  IOutput: { // field return type name
    code: 'Int'
    message: 'String'
    success: 'Boolean'
  }
  Interest: { // field return type name
    id: 'ID'
    interest_name: 'String'
    profile_interests: 'ProfileInterest'
  }
  Location: { // field return type name
    id: 'Int'
    location_name: 'String'
  }
  Message: { // field return type name
    author: 'Profile'
    conversation_id: 'String'
    createdAt: 'Date'
    id: 'String'
    message_author_id: 'String'
    message_content: 'String'
  }
  Mutation: { // field return type name
    changePassword: 'AuthOutput'
    connectBuddy: 'RelationshipOutput'
    connectTutorOrder: 'TutorOrderOutput'
    createBuddyRequest: 'CreateBuddyRequestOutput'
    createGroupConversation: 'initConversationOutput'
    createProfile: 'ProfileMutationOutput'
    createPurposeType: 'CreatePurposeTypeOutput'
    createTutorOrder: 'TutorOrderOutput'
    deleteEducation: 'ProfileMutationOutput'
    deleteTutorOrder: 'TutorOrderOutput'
    deleteTutorOrderConnect: 'TutorOrderOutput'
    deleteWorkExperience: 'ProfileMutationOutput'
    forgotPassword: 'AuthOutput'
    initConversation: 'initConversationOutput'
    login: 'AuthOutput'
    logout: 'AuthOutput'
    markCompleteTutorOrder: 'TutorOrderOutput'
    readBuddyNotifications: 'BuddyNotificationOutput'
    readMessage: 'IOutput'
    readNotification: 'NotificationMutationOutput'
    register: 'AuthOutput'
    removeAvatar: 'ProfileMutationOutput'
    removeBuddy: 'RelationshipOutput'
    removeWallpaper: 'ProfileMutationOutput'
    respondBuddy: 'RelationshipOutput'
    respondTutorOrderConnect: 'TutorOrderOutput'
    sendMessage: 'SendMessageOutput'
    updateAvatar: 'ProfileMutationOutput'
    updateBuddyRequest: 'CreateBuddyRequestOutput'
    updateIntroduction: 'ProfileMutationOutput'
    updateTutorOrder: 'TutorOrderOutput'
    updateWallpaper: 'ProfileMutationOutput'
    upsertAgeLocation: 'ProfileMutationOutput'
    upsertEducation: 'UpsertEducationOutput'
    upsertWorkExperience: 'UpsertWorkExperienceOutput'
    verifyEmail: 'AuthOutput'
    viewBuddyNotifications: 'BuddyNotificationOutput'
    viewMessage: 'IOutput'
    viewNotification: 'NotificationMutationOutput'
  }
  Notification: { // field return type name
    createdAt: 'Date'
    entity_id: 'String'
    id: 'String'
    isRead: 'Boolean'
    isViewed: 'Boolean'
    message: 'String'
    notifier: 'Profile'
    notifier_id: 'String'
    receiver_id: 'String'
    type_id: 'Int'
  }
  NotificationMutationOutput: { // field return type name
    IOutput: 'IOutput'
  }
  PageInfoCompoundIDCursor: { // field return type name
    endCursor: 'CompoundIDEndCursor'
    hasNextPage: 'Boolean'
    lastTake: 'Int'
  }
  PageInfoDataCursor: { // field return type name
    endCursor: 'Date'
    hasNextPage: 'Boolean'
    lastTake: 'Int'
  }
  PageInfoIDCursor: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    lastTake: 'Int'
  }
  Profile: { // field return type name
    birthday: 'Date'
    createdAt: 'Date'
    education: 'Education'
    gender: 'Gender'
    id: 'ID'
    location: 'Location'
    location_id: 'Int'
    profile_avatar: 'String'
    profile_avatar_public_id: 'String'
    profile_bio: 'String'
    profile_wallpaper: 'String'
    profile_wallpaper_public_id: 'String'
    tutor_mode: 'Boolean'
    user: 'User'
    work_experience: 'WorkExperience'
  }
  ProfileInterest: { // field return type name
    interest: 'Interest'
    interest_id: 'ID'
    profile: 'Profile'
    profile_id: 'ID'
  }
  ProfileMutationOutput: { // field return type name
    IOutput: 'IOutput'
    Profile: 'Profile'
  }
  Purpose: { // field return type name
    id: 'ID'
    purpose_description: 'String'
    purpose_name: 'String'
    purpose_type: 'PurposeType'
  }
  PurposeType: { // field return type name
    extened_purpose_type_data: 'JSON'
    id: 'ID'
    purpose: 'Purpose'
    purpose_id: 'String'
    purpose_type_description: 'String'
    purpose_type_name: 'String'
  }
  Query: { // field return type name
    getBuddyNotifications: 'BuddyNotificationOutput'
    getConversation: 'getConversationOutput'
    getManyBuddyRequests: 'GetManyBuddyRequestsOutput'
    getManyConversations: 'getManyConversationPutput'
    getManyInterests: 'GetManyInterestOutput'
    getManyProfiles: 'GetManyProfilesOutput'
    getManyPurposeTypes: 'GetManyPurposeTypesOutput'
    getManyPurposes: 'GetManyPurposesOutput'
    getManyTutorOrderRequests: 'GetManyTutorOrderTutorConnect'
    getManyTutorOrders: 'GetManyTutorOrdersOutput'
    getMyBuddies: 'GetMyBuddiesOutput'
    getMyBuddiesRequests: 'GetMyBuddiesOutput'
    getMyBuddyRequests: 'GetManyBuddyRequestsOutput'
    getMyTutorOrder: 'GetManyTutorOrdersOutput'
    getNotifications: 'GetNotificationOutput'
    getProfile: 'ProfileMutationOutput'
    getRelationship: 'GetRelationshipOutput'
    getSuggestedBuddyRequests: 'GetManyBuddyRequestsOutput'
    getTutorOrder: 'TutorOrderOutput'
    getTutorOrderTutorConnect: 'GetTutorOrderTutorConnectOutput'
    getUniquePurposeType: 'GetUniquePurposeType'
    getUser: 'User'
  }
  Relationship: { // field return type name
    addressee: 'Profile'
    addressee_id: 'String'
    conversation_id: 'String'
    createdAt: 'Date'
    isRead: 'Boolean'
    isViewed: 'Boolean'
    requester: 'Profile'
    requester_id: 'String'
    status: 'RelationshipStatusCode'
    updatedAt: 'Date'
  }
  RelationshipOutput: { // field return type name
    IOutput: 'IOutput'
    otherEndRelationship: 'Relationship'
    relationship: 'Relationship'
  }
  SendMessageOutput: { // field return type name
    IOutput: 'IOutput'
    Message: 'Message'
  }
  Subscription: { // field return type name
    getBuddyNotifications: 'BuddyNotificationOutput'
    getConversation: 'getConversationOutput'
    getManyConversations: 'getManyConversationPutput'
    getNotifications: 'GetNotificationOutput'
  }
  TutorOrder: { // field return type name
    createdAt: 'Date'
    id: 'String'
    isCompleted: 'Boolean'
    problem: 'String'
    student: 'Profile'
    student_id: 'String'
    tutor: 'Profile'
    tutor_id: 'String'
    tutor_order_interest: 'TutorOrderInterests'
    tutor_requirements: 'String'
    updatedAt: 'Date'
  }
  TutorOrderInterests: { // field return type name
    interest: 'Interest'
    interest_id: 'String'
    tutor_order: 'TutorOrder'
    tutor_order_id: 'String'
  }
  TutorOrderOutput: { // field return type name
    IOutput: 'IOutput'
    tutor_order: 'TutorOrder'
  }
  TutorOrderTutorConnect: { // field return type name
    status: 'TutorOrderTutorConnectStatusCode'
    tutor: 'Profile'
    tutor_id: 'String'
    tutor_order: 'TutorOrder'
    tutor_order_id: 'String'
  }
  UpdateProfilePurposesOutput: { // field return type name
    IOutput: 'IOutput'
  }
  UpsertEducationOutput: { // field return type name
    IOutput: 'IOutput'
    education: 'Education'
  }
  UpsertWorkExperienceOutput: { // field return type name
    IOutput: 'IOutput'
    work_experience: 'WorkExperience'
  }
  User: { // field return type name
    email: 'String'
    id: 'ID'
    isVerified: 'Boolean'
    profile: 'Profile'
    username: 'String'
  }
  WorkExperience: { // field return type name
    current: 'Boolean'
    id: 'String'
    joined_at: 'Date'
    left_at: 'Date'
    logo: 'String'
    logo_public_id: 'String'
    profile_id: 'String'
    work_description: 'String'
    work_position: 'String'
    workplace_name: 'String'
  }
  createPurposeOutput: { // field return type name
    IOutput: 'IOutput'
  }
  getConversationOutput: { // field return type name
    Conversation: 'Conversation'
    ConversationPageInfo: 'PageInfoIDCursor'
    IOutput: 'IOutput'
    Messages: 'Message'
  }
  getManyConversationPutput: { // field return type name
    Conversations: 'ConversationGroup'
    IOutput: 'IOutput'
    countNotViewedConversation: 'Int'
  }
  initConversationOutput: { // field return type name
    IOutput: 'IOutput'
    conversation: 'Conversation'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    changePassword: { // args
      input: NexusGenInputs['ChangePasswordInput']; // ChangePasswordInput!
    }
    connectBuddy: { // args
      input: NexusGenInputs['RelationshipInput']; // RelationshipInput!
    }
    connectTutorOrder: { // args
      where: NexusGenInputs['ConnectTutorOrderInput']; // ConnectTutorOrderInput!
    }
    createBuddyRequest: { // args
      input: NexusGenInputs['CreateBuddyRequestInput']; // CreateBuddyRequestInput!
    }
    createGroupConversation: { // args
      input: NexusGenInputs['createGroupConversationInput']; // createGroupConversationInput!
    }
    createProfile: { // args
      input: NexusGenInputs['CreateProfileInput']; // CreateProfileInput!
    }
    createPurposeType: { // args
      input: NexusGenInputs['CreatePurposeTypeInput']; // CreatePurposeTypeInput!
    }
    createTutorOrder: { // args
      input: NexusGenInputs['CreateTutorOrderInput']; // CreateTutorOrderInput!
    }
    deleteEducation: { // args
      where: NexusGenInputs['EducationWhereUniqueInput']; // EducationWhereUniqueInput!
    }
    deleteTutorOrder: { // args
      where: NexusGenInputs['TutorOrderWhereUniqueInput']; // TutorOrderWhereUniqueInput!
    }
    deleteTutorOrderConnect: { // args
      where1: NexusGenInputs['TutorOrderWhereUniqueInput']; // TutorOrderWhereUniqueInput!
      where2: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    deleteWorkExperience: { // args
      where: NexusGenInputs['WorkExperienceWhereUniqueInput']; // WorkExperienceWhereUniqueInput!
    }
    forgotPassword: { // args
      input: NexusGenInputs['ForgotPasswordInput']; // ForgotPasswordInput!
    }
    initConversation: { // args
      input: NexusGenInputs['initConversationInput']; // initConversationInput!
    }
    login: { // args
      input: NexusGenInputs['LoginInput']; // LoginInput!
    }
    markCompleteTutorOrder: { // args
      where: NexusGenInputs['MarkCompleteTutorOrderInput']; // MarkCompleteTutorOrderInput!
    }
    readBuddyNotifications: { // args
      where: NexusGenInputs['ReadBuddyNotificationsInput']; // ReadBuddyNotificationsInput!
    }
    readMessage: { // args
      where: NexusGenInputs['ConversationGroupWhereUniqueInput']; // ConversationGroupWhereUniqueInput!
    }
    readNotification: { // args
      where: NexusGenInputs['NotificationWhereUniqueInput']; // NotificationWhereUniqueInput!
    }
    register: { // args
      input: NexusGenInputs['RegisterInput']; // RegisterInput!
    }
    removeAvatar: { // args
      input: NexusGenInputs['DestroyImageInput']; // DestroyImageInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    removeBuddy: { // args
      input: NexusGenInputs['RelationshipInput']; // RelationshipInput!
    }
    removeWallpaper: { // args
      input: NexusGenInputs['DestroyImageInput']; // DestroyImageInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    respondBuddy: { // args
      input: NexusGenInputs['RelationshipInput']; // RelationshipInput!
    }
    respondTutorOrderConnect: { // args
      where: NexusGenInputs['ResondTutorOrderConnectInput']; // ResondTutorOrderConnectInput!
    }
    sendMessage: { // args
      input: NexusGenInputs['SendMessageInput']; // SendMessageInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    updateAvatar: { // args
      input: NexusGenInputs['ChangeImageInput']; // ChangeImageInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    updateBuddyRequest: { // args
      input: NexusGenInputs['UpdateBuddyRequestInput']; // UpdateBuddyRequestInput!
      where: NexusGenInputs['BuddyRequestWhereUniqueInput']; // BuddyRequestWhereUniqueInput!
    }
    updateIntroduction: { // args
      input: NexusGenInputs['updateIntroductionInput']; // updateIntroductionInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    updateTutorOrder: { // args
      input: NexusGenInputs['CreateTutorOrderInput']; // CreateTutorOrderInput!
      where: NexusGenInputs['TutorOrderWhereUniqueInput']; // TutorOrderWhereUniqueInput!
    }
    updateWallpaper: { // args
      input: NexusGenInputs['ChangeImageInput']; // ChangeImageInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    upsertAgeLocation: { // args
      input: NexusGenInputs['UpsertAgeLocationInput']; // UpsertAgeLocationInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    upsertEducation: { // args
      input: NexusGenInputs['UpsertEducationInput']; // UpsertEducationInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    upsertWorkExperience: { // args
      input: NexusGenInputs['UpsertWorkExperienceInput']; // UpsertWorkExperienceInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    verifyEmail: { // args
      input: NexusGenInputs['VerifyEmailInput']; // VerifyEmailInput!
    }
    viewBuddyNotifications: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    viewMessage: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    viewNotification: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
  }
  Query: {
    getBuddyNotifications: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    getConversation: { // args
      page: NexusGenInputs['ConversationPageInput']; // ConversationPageInput!
      where: NexusGenInputs['ConversationWhereUniqueInput']; // ConversationWhereUniqueInput!
    }
    getManyBuddyRequests: { // args
      where: NexusGenInputs['GetManyBuddyRequestsInput']; // GetManyBuddyRequestsInput!
    }
    getManyConversations: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    getManyInterests: { // args
      where: NexusGenInputs['getManyInterestsInput']; // getManyInterestsInput!
    }
    getManyProfiles: { // args
      where: NexusGenInputs['GetManyProfilesInput']; // GetManyProfilesInput!
    }
    getManyPurposeTypes: { // args
      where: NexusGenInputs['GetManyPurposeTypesInput']; // GetManyPurposeTypesInput!
    }
    getManyPurposes: { // args
      where: NexusGenInputs['GetManyPurposesInput']; // GetManyPurposesInput!
    }
    getManyTutorOrderRequests: { // args
      where: NexusGenInputs['TutorOrderWhereUniqueInput']; // TutorOrderWhereUniqueInput!
    }
    getManyTutorOrders: { // args
      where: NexusGenInputs['GetManyTutorOrdersInput']; // GetManyTutorOrdersInput!
    }
    getMyBuddies: { // args
      input: NexusGenInputs['GetMyBuddiesInput']; // GetMyBuddiesInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    getMyBuddiesRequests: { // args
      input: NexusGenInputs['GetMyBuddiesInput']; // GetMyBuddiesInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    getMyBuddyRequests: { // args
      input: NexusGenInputs['GetMyBuddyRequestsInput']; // GetMyBuddyRequestsInput!
    }
    getMyTutorOrder: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    getNotifications: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    getProfile: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    getRelationship: { // args
      where: NexusGenInputs['GetRelationshipInput']; // GetRelationshipInput!
    }
    getSuggestedBuddyRequests: { // args
      where: NexusGenInputs['GetSuggestedBuddyRequests']; // GetSuggestedBuddyRequests!
    }
    getTutorOrder: { // args
      where: NexusGenInputs['TutorOrderWhereUniqueInput']; // TutorOrderWhereUniqueInput!
    }
    getTutorOrderTutorConnect: { // args
      where_1: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
      where_2: NexusGenInputs['TutorOrderWhereUniqueInput']; // TutorOrderWhereUniqueInput!
    }
    getUniquePurposeType: { // args
      where: NexusGenInputs['GetUniquePurposeTypeInput']; // GetUniquePurposeTypeInput!
    }
  }
  Subscription: {
    getBuddyNotifications: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    getConversation: { // args
      where: NexusGenInputs['ConversationGroupWhereUniqueInput']; // ConversationGroupWhereUniqueInput!
    }
    getManyConversations: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    getNotifications: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}